// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Rota.Stream.AvroContracts
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class RotaCreated : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""RotaCreated"",""namespace"":""Rota.Stream.AvroContracts"",""fields"":[{""name"":""RotaId"",""type"":""string""},{""name"":""EventId"",""type"":""string""},{""name"":""TimeFrame"",""type"":{""type"":""record"",""name"":""TimeFrame"",""namespace"":""Rota.Stream.AvroContracts"",""fields"":[{""name"":""StartDate"",""type"":""string""},{""name"":""EndDate"",""type"":""string""}]}}]}");
		private string _RotaId;
		private string _EventId;
		private Rota.Stream.AvroContracts.TimeFrame _TimeFrame;
		public virtual Schema Schema
		{
			get
			{
				return RotaCreated._SCHEMA;
			}
		}
		public string RotaId
		{
			get
			{
				return this._RotaId;
			}
			set
			{
				this._RotaId = value;
			}
		}
		public string EventId
		{
			get
			{
				return this._EventId;
			}
			set
			{
				this._EventId = value;
			}
		}
		public Rota.Stream.AvroContracts.TimeFrame TimeFrame
		{
			get
			{
				return this._TimeFrame;
			}
			set
			{
				this._TimeFrame = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.RotaId;
			case 1: return this.EventId;
			case 2: return this.TimeFrame;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.RotaId = (System.String)fieldValue; break;
			case 1: this.EventId = (System.String)fieldValue; break;
			case 2: this.TimeFrame = (Rota.Stream.AvroContracts.TimeFrame)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
