// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Rota.Stream.AvroContracts
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class TimeFrame : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"TimeFrame\",\"namespace\":\"Rota.Stream.AvroContracts\",\"fiel" +
				"ds\":[{\"name\":\"StartDate\",\"type\":\"string\"},{\"name\":\"EndDate\",\"type\":\"string\"}]}");
		private string _StartDate;
		private string _EndDate;
		public virtual Schema Schema
		{
			get
			{
				return TimeFrame._SCHEMA;
			}
		}
		public string StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				this._StartDate = value;
			}
		}
		public string EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				this._EndDate = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.StartDate;
			case 1: return this.EndDate;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.StartDate = (System.String)fieldValue; break;
			case 1: this.EndDate = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
