// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Staff.Stream.AvroContracts
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class StaffMemberTerminated : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""StaffMemberTerminated"",""namespace"":""Staff.Stream.AvroContracts"",""fields"":[{""name"":""TraceId"",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""StaffMemberId"",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""EventId"",""type"":""string""},{""name"":""TimeFrame"",""type"":{""type"":""record"",""name"":""TimeFrame"",""namespace"":""Staff.Stream.AvroContracts"",""fields"":[{""name"":""StartDate"",""type"":""string""},{""name"":""EndDate"",""type"":""string""}]}}]}");
		private System.Guid _TraceId;
		private System.Guid _StaffMemberId;
		private string _EventId;
		private Staff.Stream.AvroContracts.TimeFrame _TimeFrame;
		public virtual Schema Schema
		{
			get
			{
				return StaffMemberTerminated._SCHEMA;
			}
		}
		public System.Guid TraceId
		{
			get
			{
				return this._TraceId;
			}
			set
			{
				this._TraceId = value;
			}
		}
		public System.Guid StaffMemberId
		{
			get
			{
				return this._StaffMemberId;
			}
			set
			{
				this._StaffMemberId = value;
			}
		}
		public string EventId
		{
			get
			{
				return this._EventId;
			}
			set
			{
				this._EventId = value;
			}
		}
		public Staff.Stream.AvroContracts.TimeFrame TimeFrame
		{
			get
			{
				return this._TimeFrame;
			}
			set
			{
				this._TimeFrame = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.TraceId;
			case 1: return this.StaffMemberId;
			case 2: return this.EventId;
			case 3: return this.TimeFrame;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.TraceId = (System.Guid)fieldValue; break;
			case 1: this.StaffMemberId = (System.Guid)fieldValue; break;
			case 2: this.EventId = (System.String)fieldValue; break;
			case 3: this.TimeFrame = (Staff.Stream.AvroContracts.TimeFrame)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
